In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = pd.read_csv('C:/projects/WaferFaultDetection1/Training_FileFromDB/InputFile.csv')
data2 = pd.read_csv('Training_Raw_files_validated/finaltrainingdata.csv')
data3 = pd.read_csv('Prediction_Raw_Files_Validated/finalpredictiondata.csv')

In [4]:
data.head()

,Wafer,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 6,Sensor - 7,Sensor - 8,Sensor - 9,...,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590,Output
0,1201,3045.98,2544.85,2253.3444,1873.8678,1.1691,100.0,94.9722,0.1210,1.4752,...,NaN,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,-1
1,1202,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.0,100.6222,0.1250,1.4536,...,NaN,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,-1
2,1203,3071.18,2489.86,2195.3000,1151.8233,0.9220,100.0,103.5467,0.1232,1.4826,...,NaN,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,-1
3,1204,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.0,100.1367,0.1243,1.4645,...,NaN,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,-1
4,1205,3196.21,2413.39,2255.5222,1763.0739,1.2226,100.0,101.5878,0.1200,1.4845,...,353.8319,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,-1

In [10]:
#data.to_csv('Training_Raw_files_validated/finaltrainingdata.csv', index=False)

In [5]:
data.Output.value_counts()

-1    4800
 1     222
Name: Output, dtype: int64

In [6]:
4800 + 222

5022

In [7]:
data2.head()

,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 7,Sensor - 8,Sensor - 9,Sensor - 10,Sensor - 11,...,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590,Cluster,Labels
0,3045.98,2544.85,2253.3444,1873.8678,1.1691,94.9722,0.1210,1.4752,0.0084,0.0009,...,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279,0,0
1,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.6222,0.1250,1.4536,-0.0110,-0.0035,...,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279,2,0
2,3071.18,2489.86,2195.3000,1151.8233,0.9220,103.5467,0.1232,1.4826,0.0136,0.0009,...,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279,0,0
3,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.1367,0.1243,1.4645,0.0001,0.0067,...,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279,0,0
4,3196.21,2413.39,2255.5222,1763.0739,1.2226,101.5878,0.1200,1.4845,-0.0037,0.0049,...,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319,0,0

In [9]:
data2.Labels.value_counts()

0    4800
1     222
Name: Labels, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(data2.drop(['Cluster', 'Labels'], axis=1), data2.Labels,
                                                    test_size=0.2,
                                                    random_state=0,
                                                    stratify=data2.Labels)

In [17]:
y_train.value_counts()

0    3839
1     178
Name: Labels, dtype: int64

In [18]:
y_test.value_counts()

0    961
1     44
Name: Labels, dtype: int64

In [19]:
import pickle

In [22]:
model = pickle.load(open('C:/projects/WaferFaultDetection1/models/RandomForest2/RandomForest2.sav', 'rb'))

In [23]:
y = model.predict(data2.drop(['Cluster', 'Labels'], axis=1))

In [25]:
data3.head()

,Wafer,Sensor - 1,Sensor - 2,Sensor - 3,Sensor - 4,Sensor - 5,Sensor - 7,Sensor - 8,Sensor - 9,Sensor - 10,...,Sensor - 581,Sensor - 582,Sensor - 583,Sensor - 584,Sensor - 585,Sensor - 586,Sensor - 587,Sensor - 588,Sensor - 589,Sensor - 590
0,1201.0,3045.98,2544.85,2253.3444,1873.8678,1.1691,94.9722,0.1210,1.4752,0.0084,...,0.004233,47.958333,0.4948,0.0123,0.0033,2.4804,0.0291,0.0102,0.0033,35.0279
1,1202.0,3151.98,2563.75,2175.2556,1022.1660,1.2833,100.6222,0.1250,1.4536,-0.0110,...,0.007500,111.563900,0.5063,0.0113,0.0031,2.2284,0.0291,0.0102,0.0033,35.0279
2,1203.0,3071.18,2489.86,2195.3000,1151.8233,0.9220,103.5467,0.1232,1.4826,0.0136,...,0.004733,83.487367,0.5033,0.0112,0.0029,2.2320,0.0291,0.0102,0.0033,35.0279
3,1204.0,2958.46,2523.78,2171.8556,1156.6018,1.4025,100.1367,0.1243,1.4645,0.0001,...,0.003967,38.998500,0.4954,0.0136,0.0033,2.7511,0.0291,0.0102,0.0033,35.0279
4,1205.0,3196.21,2413.39,2255.5222,1763.0739,1.2226,101.5878,0.1200,1.4845,-0.0037,...,0.005700,353.831900,0.5058,0.0094,0.0026,1.8673,0.0053,0.0188,0.0057,353.8319

In [26]:
data4 = pd.read_csv('Prediction_Output_File/Predictions.csv')

In [27]:
data4.head()

   Unnamed: 0   Wafer Prediction
0         0.0  1201.0          0
1         1.0  1203.0          0
2         2.0  1204.0          0
3         3.0  1205.0          0
4         4.0  1206.0          0